name: Singularity Setup
description: All steps to use/build Singularity container
runs:
  using: composite
  steps:
    - name: Setup apptainer
      uses: eWaterCycle/setup-apptainer@v2.0.0
    
    - name: Get container from cache
      id: cache-sif
      uses: actions/cache@v4
      with:
        path: .singularity/image.sif
        key: ${{ hashFiles('container.def', 'bin/.container-tag') }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libruby3.2 ruby3.2-dev
      shell: bash

    - name: Set up Ruby
      id: setup-ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Get node_modules cache
      uses: actions/cache@v4
      id: cache-node
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install node dependencies
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Rebuild problematic gems
      run: |
        for gem in psych:5.2.6 stringio:3.1.7 date:3.4.1; do
          name=${gem%:*}
          version=${gem#*:}
          gem pristine $name --version $version || true
        done
      shell: bash
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libruby3.2 ruby3.2-dev
      shell: bash

    - name: Set up Ruby
      id: setup-ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Get node_modules cache
      uses: actions/cache@v4
      id: cache-node
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Rebuild problematic gems
      run: |
        for gem in psych:5.2.6 stringio:3.1.7 date:3.4.1; do
          name=${gem%:*}
          version=${gem#*:}
          gem pristine $name --version $version || true
        done
      shell: bash
        restore-keys: |
          ${{ runner.os }}-ruby-${{ env.ruby-version }}-gems-
    - if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
      name: Build container
      run: ./bin/build_container
      shell: bash
    - name: Setup project
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install
        ./bin/setup
      shell: bash
