name: Singularity Setup
description: All steps to use/build Singularity container
runs:
  using: composite
  steps:
    - name: Setup apptainer
      uses: eWaterCycle/setup-apptainer@v2.0.0
    - name: Get container from cache
      id: cache-sif
      uses: actions/cache@v4
      with:
        path: .singularity/image.sif
        key: ${{ hashFiles('container.def', 'bin/.container-tag') }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
      shell: bash
    
    - name: Rebuild gems
      run: |
        gem pristine --all
        gem pristine psych --version 5.2.6
        gem pristine stringio --version 3.1.7
        gem pristine date --version 3.4.1
      shell: bash

    - name: Install node dependencies
      run: npm ci
      shell: bash

    - name: Get gems and node files from cache
      id: cache-bundle-npm
      uses: actions/cache@v4
      with:
        path: |
          vendor/bundle
          node_modules
        key: ${{ runner.os }}-ruby-${{ env.ruby-version }}-gems-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ env.ruby-version }}-gems-
    - if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
      name: Build container
      run: ./bin/build_container
      shell: bash
    - name: Setup project
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install
        ./bin/setup
      shell: bash
